animes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'animes'


urlpatterns = [
    path('', views.home, name="home"),
    path('animes/genero/<int:genero_id>/', views.genero, name="genero"),
    path('animes/create/', views.create_anime, name="create"),
    path('<int:id>/', views.detail, name='detail'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animes.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

animes/models.py
from django.contrib.auth.models import User
from django.db import models


class Genero(models.Model):
    genero = models.CharField(max_length=20)

    def __str__(self):
        return (self.genero)


class Anime(models.Model):
    nome_anime = models.CharField(max_length=65)
    slug = models.SlugField()
    resumo = models.TextField()
    resumo_is_html = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    publicado = models.BooleanField(default=False)
    img_anime = models.ImageField(upload_to='animes/covers/%Y/%m/%d/')
    genero = models.ForeignKey(
        Genero, on_delete=models.SET_NULL, null=True
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True
    )
    episodios = models.IntegerField()

    def __str__(self):
        return (self.nome_anime)

animes/views.py
from django.shortcuts import render, redirect
from .models import Anime
from django.forms import modelform_factory
from django.utils.text import slugify
from django.utils import timezone


def home(request):
    animes = Anime.objects.all().order_by('-id')
    return render(request, 'animes/pages/home.html', context={
        'animes': animes
    })


def genero(request, genero_id):
    animes = Anime.objects.filter(
        genero__id=genero_id
    ).order_by('-id')
    return render(request, 'animes/pages/home.html', context={
        'animes': animes,
    })


def detail(request, id):
    animes = Anime.objects.filter(
       __id=id
    )
    return render(request, 'animes/pages/anime-view.html', context={
        'animes': animes,
        'is_resume_page': True,
    })


def create_anime(request):
    AnimeForm = modelform_factory(Anime, exclude=('slug', 'data_criacao'))

    if request.method == 'POST':
        form = AnimeForm(request.POST, request.FILES)
        if form.is_valid():
            anime = form.save(commit=False)
            anime.slug = slugify(anime.nome_anime)
            anime.data_criacao = timezone.now()
            anime.save()

            return redirect('animes:home')
    else:
        form = AnimeForm()

    return render(request, 'animes/pages/create.html', context={
        'form': form,
    })

animes/templates/animes/pages/anime-view.html
{% extends "global/base.html" %}
{% block title %}Details | {% endblock title %}
{% block content %}
<div class="main-content">
    {% include 'animes/partials/anime-window.html' %}
</div>              
{% endblock content %} 

animes/templates/animes/pages/create.html
{% extends "global/base.html" %}
{% block title %}Create | {% endblock title %}
{% block content %}
<div class="main-content">
    {% include 'animes/partials/form.html' %}
</div>              
{% endblock content %} 

animes/templates/animes/pages/home.html
{% extends "global/base.html" %}

{% block title %}Home | {% endblock title %}

{% block  content %}
<div class="grid-container">
    {% for anime in animes %}
        {% include 'animes/partials/anime-window.html' %}
    {% endfor %}
</div>      
{% endblock content %}          

animes/templates/animes/partials/anime-window.html
<div class="window anime">
    <div class="main-img">
        <img src="media/{{anime.img_anime}}" alt="Foto_anime">
        <div class="anime-title link-anima">
            <h2><a href="{% url 'animes:detail' anime.id %}">
                {{ anime.nome_anime }}
            </a></h2>                    
        </div>
    </div>
    <div class="anime-info">
        <div class="author-info">
            <div class="link-anima">
                <i class="fa-solid fa-user"> </i>
                {%if anime.author.first_name %}
                    <a href="#">{{ anime.author.first_name }} {{ anime.author.last_name }}</a>
                {% else %}
                    <a href="#">{{ anime.author.username }}</a>
                {% endif %}
            </div>
            <div>
                <i class="fa-solid fa-calendar-days"> </i>
                <span>{{anime.data_criacao|date:"d/m/Y"}}</span>
            </div>
        </div>
        {%if is_resume_page is not True%}
            <ul class="text-color">
                <li class="link-anima">Gênero: <a href="{% url 'animes:genero' genero_id=anime.genero.id %}">{{anime.genero}}</a></li>
                <li>Episódios: {{anime.episodios}}</li>
            </ul>
        {%endif%}
        {%if is_resume_page is True%}
            <div class="resumeanime">
                {{anime.resumo}}
            </div>
        {%endif%}
    </div>
</div>

animes/templates/animes/partials/footer.html
<footer class="main-footer link-anima">
    <div><a href="https://github.com/Rychard2107/">By Rychardson Zafler</a></div>
    <div>
        <a href="http://www.djangoproject.com/">Powered by Django</a>
    </div>
</footer>

animes/templates/animes/partials/form.html
<h1>Criar Anime</h1>

<form action="{% url 'animes:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

animes/templates/animes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css"
    integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css"
    integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css"
    integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Andika:wght@700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'animes/css/styles.css'%}">
<link rel="stylesheet" href="{% static 'global/css/global_styles.css'%}">

animes/templates/animes/partials/header.html
<header class="header-content-conteiner">
    <div class="header-content" >
        <div style="a {color: white}">
            <a href="{% url 'animes:create' %}">Criar anime</a>
        </div>
        <h1 class="heading">
            <i class="fa-solid fa-fire-flame-curved heading"></i>
            <span class='link-anima'>
                <a href="/">Fire animes</a>
            </span>
        </h1>
        <form action="" class="search-form width-form">
            <input type="search" class="search-input">
            <button class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>    
    </div>
</header>